volumes:
  upload_tmp:

services:
  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-${IMAGE_ENV}
    build: ./backend
    container_name: load_files_api
    env_file: ./backend/.env
    environment:
      - ENVIRONMENT=production
    ports:
      - "8005:8005"
    restart: unless-stopped
    tmpfs:
      - /dev/shm:size=1g
    volumes:
      - upload_tmp:/dev/shm/load_files_uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: ./backend
    container_name: load_files_worker
    env_file: ./backend/.env
    environment:
      - ENVIRONMENT=production
    command: celery -A load_files.celery_app worker -l info -c 2 --max-tasks-per-child 10
    restart: unless-stopped
    tmpfs:
      - /dev/shm:size=1g
    volumes:
      - upload_tmp:/dev/shm/load_files_uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
